Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Models/TipoMascotaView.cs
using VeterinariaWebApp.Entities;

namespace VeterinariaWebApp.ClientMvc.Models
{
    public class TipoMascotaView
    {
        public ICollection<TipoMascotaInfo> TipoMascotas { get; set; } = new List<TipoMascotaInfo>();
        public DeleteConfirmationModel Delete { get; set; } = new() { Controlador = "TipoMascota" };
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Models/TipoMascotaViewModel.cs
namespace VeterinariaWebApp.ClientMvc.Models
{
    public class TipoMascotaViewModel
    {
        public int Id { get; set; }
        public string Nombres { get; set; } = default!;
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Controllers/TipoMascotasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VeterinariaWebApp.ClientMvc.Models;
using VeterinariaWebApp.Entities;
using VeterinariaWebApp.Repositories.Interfaces;

namespace VeterinariaWebApp.ClientMvc.Controllers
{
    [Authorize(Roles = Constantes.RolAdmin)]
    public class TipoMascotasController : Controller
    {
        private readonly ITipoMascotaRepository _repository;

        public TipoMascotasController(ITipoMascotaRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index(string? nombre)
        {
            ViewBag.Nombre = nombre;

            return View(new TipoMascotaView()
            {
                TipoMascotas = await _repository.GetAllAsync(nombre)
            });
        }
        [Authorize(Roles = Constantes.RolAdmin)]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Create(TipoMascotaViewModel request)
        {
            await _repository.AddAsync(
                new TipoMascota
                {
                    Nombres = request.Nombres
                });

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(int id)
        {
            var entity = await _repository.FindByIdAsync(id);
            if (entity is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new TipoMascotaViewModel
            {
                Nombres = entity.Nombres,
            };

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(TipoMascotaViewModel request)
        {
            var cliente = await _repository.FindByIdAsync(request.Id);

            if (cliente is null)
            {
                ModelState.AddModelError("ID", "No se encontro el registro");
                return View();
            }

            cliente.Nombres = request.Nombres;

            await _repository.UpdateAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _repository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/TipoMascotas/Create.cshtml
@model TipoMascotaViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Crear tipo de mascota</h2>

<form asp-controller="TipoMascotas" asp-action="Create" method="post">
    <partial name="_EditTipoMascota" model="Model" />
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/TipoMascotas/Edit.cshtml
@model TipoMascotaViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Actualizar tipo de mascota</h2>

<form asp-controller="TipoMascotas" asp-action="Edit" method="post">
    <partial name="_EditTipoMascota" model="Model" />
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/TipoMascotas/Index.cshtml
@using VeterinariaWebApp.Entities;
@model TipoMascotaView
@{
    ViewData["Title"] = "Tipo de Mascotas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mt-5">Lista de Tipo de Mascotas</h1>

<form asp-action="Index" method="get">
    <div class="row justify-content-center mt-3 mb-4">
        <div class="col-sm-6 col-md-8 col-xl-12">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar..." name="nombre"
                       value="@ViewBag.Nombre" />
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="oi oi-magnifying-glass"></i>
                </button>
            </div>
        </div>
    </div>
</form>

<a class="btn btn-primary" asp-action="Index"><i class="oi oi-reload me-1"></i>Cargar Lista</a>
<a class="btn btn-outline-primary" asp-action="Create"><i class="oi oi-plus me-1"></i>Crear</a>

<hr />

@if (Model.TipoMascotas.Count == 0)
{
    <p class="alert alert-warning">No hay datos para mostrar</p>
}
else
{
    <table class="table table-primary table-hover table-bordered">
        <thead>
            <tr class="table-dark">
                <th>ID</th>
                <th>Nombres</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.TipoMascotas)
            {
                <tr class="table-light">
                    <td>@item.Id</td>
                    <td>@item.Nombres</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit"
                           asp-route-id="@item.Id"><i class="oi oi-pencil"></i></a>

                        @if (User.IsInRole(Constantes.RolAdmin))
                        {
                            <a class="btn btn-danger btnEliminar" data-id="@item.Id"><i class="oi oi-trash"></i></a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}



@section Scripts
    {
    @{
        <partial name="_DeleteConfirmation" model="@Model.Delete" />
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/TipoMascotas/_EditTipoMascota.cshtml
@model TipoMascotaViewModel

<div asp-validation-summary="All" class="text-danger"></div>
<div class="row row-cols-md-2 row-cols-lg-1">
    <div class="col">
        <div class="mb-3 row">
            <label class="col-sm-2 form-label" asp-for="Nombres">Nombre :</label>
            <div class="col-sm-6">
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary w-25"><i class="oi oi-plus me-1"></i>Grabar</button>

</div>