Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Controllers/CitasController.cs
using Humanizer.Configuration;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Collections.Generic;
using System;
using VeterinariaWebApp.ClientMvc.Models;
using VeterinariaWebApp.DataAccess.Migrations;
using VeterinariaWebApp.Entities;
using VeterinariaWebApp.Repositories.Implementaciones;
using VeterinariaWebApp.Repositories.Interfaces;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace VeterinariaWebApp.ClientMvc.Controllers
{
    [Authorize]
    public class CitasController : Controller
    {
        private readonly ICitaRepository _repository;
        private readonly IClienteRepository _clienteRepository;
        private readonly IMascotaRepository _mascotaRepository;
        private readonly IServicioRepository _servicioRepository;

        public CitasController(ICitaRepository repository, IClienteRepository clienteRepository, IMascotaRepository mascotaRepository, IServicioRepository servicioRepository)
        {
            _repository = repository;
            _clienteRepository = clienteRepository;
            _mascotaRepository = mascotaRepository;
            _servicioRepository = servicioRepository;
        }

        public async Task<IActionResult> Index(string? nombre)
        {
            ViewBag.Nombre = nombre;
            return View(new CitaView()
            {
                Citas = await _repository.GetAllAsync(nombre)
            });
        }
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
           
            var entity = await _repository.FindByIdAsync(id);

            if (entity is null)
            {
                return RedirectToAction("Index", "Home");
            }

           
            var clienteId = entity.ClienteId ?? 0; 
            var mascotaId = entity.MascotaId ?? 0; 
            var servicioId = entity.ServicioId ?? 0;

            var cliente = await _clienteRepository.FindByIdAsync(clienteId);
            var mascota = await _mascotaRepository.FindByIdAsync(mascotaId);
            var servicio = await _servicioRepository.FindByIdAsync(servicioId);

            
            var model = new CitaInfo
            {
                Id = entity.Id,
                FechaHora = entity.FechaHora,
                Motivo = entity.Motivo,
                ClienteId = clienteId,
                Cliente = cliente != null ? cliente.Nombres + " " + cliente.Apellidos : string.Empty,
                MascotaId = mascotaId,
                FotoMascota = mascota != null ? mascota.UrlImagen : string.Empty,
                Mascota = mascota != null ? mascota.Nombres : string.Empty,
                ServicioId = servicioId,
                Servicio = servicio != null ? servicio.Nombres : string.Empty,
                PrecioUnitario = servicio != null ? servicio.PrecioUnitario : decimal.Zero
            };

            return View(model);
        }


        public async Task<IActionResult> Create()
        {
            var viewModel = new CitaViewModel
            {
                Clientes = await _clienteRepository.ListAsync(),
                Mascotas = await _mascotaRepository.ListAsync(),
                Servicios = await _servicioRepository.ListAsync()
            };

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Create(CitaViewModel request)
        {
            await _repository.AddAsync(
                new Cita
                {
                    FechaHora = DateTime.Now,
                    Motivo = request.Motivo,
                    ClienteId = request.ClienteId,
                    MascotaId = request.MascotaId,
                    ServicioId = request.ServicioId
                });

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(int id)
        {
            var entity = await _repository.FindByIdAsync(id);
            if (entity is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new CitaViewModel
            {
                FechaHora = entity.FechaHora,
                Motivo = entity.Motivo,
                ClienteId = entity.ClienteId ?? 0,
                Id = entity.Id,
                Clientes = await _clienteRepository.ListAsync(),
                MascotaId = entity.MascotaId ?? 0,
                Mascotas = await _mascotaRepository.ListAsync(),
                ServicioId = entity.ServicioId ?? 0,
                Servicios = await _servicioRepository.ListAsync()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(CitaViewModel request)
        {
            var cita = await _repository.FindByIdAsync(request.Id);

            if (cita is null)
            {
                ModelState.AddModelError("ID", "No se encontro el registro");
                return View();
            }

            cita.Motivo = request.Motivo;
            cita.ClienteId = request.ClienteId;
            cita.MascotaId = request.MascotaId;
            cita.ServicioId = request.ServicioId;

            await _repository.UpdateAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _repository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VeterinariaWebApp.ClientMvc.Models;
using VeterinariaWebApp.Entities;
using VeterinariaWebApp.Repositories.Interfaces;

namespace VeterinariaWebApp.ClientMvc.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private readonly IClienteRepository _repository;

        public ClientesController(IClienteRepository repository)
        {
            _repository = repository;
        }
        public async Task<IActionResult> Index(string? nombre)
        {
            ViewBag.Nombre = nombre;

            return View(new ClienteView()
            {
                Clientes = await _repository.GetAllAsync(nombre)
            });
        }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Create(ClienteViewModel request)
        {
            await _repository.AddAsync(
                new Cliente
                {
                    Nombres = request.Nombres,
                    Apellidos = request.Apellidos,
                    Email = request.Email,
                    Telefono = request.Telefono,
                    FechaNacimiento = request.FechaNacimiento,
                    Direccion = request.Direccion
                });

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(int id)
        {
            var entity = await _repository.FindByIdAsync(id);
            if (entity is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ClienteViewModel
            {
                Nombres = entity.Nombres,
                Apellidos = entity.Apellidos,
                Email = entity.Email,
                Telefono = entity.Telefono,
                FechaNacimiento = entity.FechaNacimiento,
                Direccion = entity.Direccion
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(ClienteViewModel request)
        {
            var cliente = await _repository.FindByIdAsync(request.Id);

            if (cliente is null)
            {
                ModelState.AddModelError("ID", "No se encontro el registro");
                return View();
            }

            cliente.Nombres = request.Nombres;
            cliente.Apellidos = request.Apellidos;
            cliente.Email = request.Email;
            cliente.Telefono = request.Telefono;
            cliente.FechaNacimiento = request.FechaNacimiento;
            cliente.Direccion = request.Direccion;

            await _repository.UpdateAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _repository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Controllers/MascotasController.cs
using Azure.Core;
using VeterinariaWebApp.ClientMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using VeterinariaWebApp.ClientMvc.Models;
using VeterinariaWebApp.Entities;
using VeterinariaWebApp.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace VeterinariaWebApp.ClientMvc.Controllers
{
    [Authorize]
    public class MascotasController : Controller
    {
        private readonly IMascotaRepository _repository;
        private readonly IClienteRepository _clienteRepository;
        private readonly ITipoMascotaRepository _tipoMascota;
        private readonly IFileUploader _fileUploader;

        public MascotasController(IMascotaRepository repository, IClienteRepository clienteRepository, ITipoMascotaRepository tipoMascota, IFileUploader fileUploader)
        {
            _repository = repository;
            _clienteRepository = clienteRepository;
            _tipoMascota = tipoMascota;
            _fileUploader = fileUploader;
        }

        public async Task<IActionResult> Index(string? nombre)
        {
            ViewBag.Nombre = nombre;
            return View(new MascotaView()
            {
                Mascotas = await _repository.GetAllAsync(nombre)
                
            });
        }
       

        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Create()
        {
            var viewModel = new MascotaViewModel
            {
                TiposMascotas = await _tipoMascota.ListAsync(),
                Clientes = await _clienteRepository.ListAsync()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Create(MascotaViewModel request)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = new Mascota
                    {
                        Nombres = request.Nombres,
                        Raza = request.Raza,
                        FechaNacimiento = request.FechaNacimiento,
                        ClienteId = request.ClienteId,
                        TipoMascotaId = request.TipoMascotaId,
                        UrlImagen = request.UrlImagen
                    };

                    // Procesa la carga de la imagen si existe
                    var file = HttpContext.Request.Form.Files.FirstOrDefault();
                    if (file is not null)
                    {
                        var tupla = await _fileUploader.UploadFileAsync(file);
                        if (!string.IsNullOrEmpty(tupla.MensajeError))
                        {
                            ModelState.AddModelError("Archivo", tupla.MensajeError);
                            return View(request);
                        }
                        entity.UrlImagen = tupla.Url;
                    }
                    else
                    {
                        entity.UrlImagen = null;
                    }

                    await _repository.AddAsync(entity);

                    return RedirectToAction(nameof(Index));
                }

                // Si ModelState no es válido, vuelve a mostrar la vista con los errores
                return View(request);
            }
            catch (Exception ex)
            {
                ViewData["Error"] = ex.Message;
                return View(request);
            }
        }

        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(int id)
        {
            var entity = await _repository.FindByIdAsync(id);
            if (entity is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new MascotaViewModel
            {
                Nombres = entity.Nombres,
                Raza = entity.Raza,
                FechaNacimiento = entity.FechaNacimiento,
                ClienteId = entity.ClienteId ?? 0,
                Clientes = await _clienteRepository.ListAsync(),
                Id = entity.Id,
                TipoMascotaId = entity.TipoMascotaId ?? 0,
                TiposMascotas = await _tipoMascota.ListAsync(),
                UrlImagen = entity.UrlImagen
                
                
            };

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Edit(MascotaViewModel request)
        {
                var cita = await _repository.FindByIdAsync(request.Id);

                if (cita is null)
                {
                    ModelState.AddModelError("ID", "No se encontro el registro");
                    return View();
                }

                cita.Nombres = request.Nombres;
                cita.Raza = request.Raza;
                cita.FechaNacimiento = request.FechaNacimiento;
                cita.ClienteId = request.ClienteId;
                cita.TipoMascotaId = request.TipoMascotaId;

                var imageFile = HttpContext.Request.Form.Files.FirstOrDefault();
                if (imageFile is not null)
                {
                    var tupla = await _fileUploader.UploadFileAsync(imageFile);
                    if (!string.IsNullOrEmpty(tupla.MensajeError))
                    {
                        ModelState.AddModelError("imageFile", tupla.MensajeError);
                        return View();
                    }
                    cita.UrlImagen = tupla.Url;
                }

                await _repository.UpdateAsync();


                return RedirectToAction(nameof(Index));
            }
        
   

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _repository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/Shared/_CitaCard.cshtml
@using VeterinariaWebApp.Entities;
@model CitaInfo

<div class="col mb-5">
    <div class="card h-100">
        <div>
            <img class="card-img-top border-dark border-1 producto-card"
                 src="@Model.FotoMascota" />
        </div>
        <div class="card-body p-4 text-center">
            <h5 class="fw-bolder">@Model.Motivo</h5>
            <span>@Model.Mascota</span> <br />
            <span>@Model.Servicio</span> <br />
            <span>S/.@Model.PrecioUnitario</span>
            <span></span>
        </div>
        <div class="card-footer p-3 pt-1 border-top-0 bg-transparent">
            <div class="text-center">
                <a class="btn btn-outline-primary mt-auto" asp-controller="Citas"
                asp-action="Detail" asp-route-id="@Model.Id">
                    Ver Cita Completa
                </a>
            </div>
        </div>
    </div>
</div>

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/Shared/_DeleteConfirmation.cshtml
@model DeleteConfirmationModel

<script>
    document.addEventListener('DOMContentLoaded', function () {
        let btnEliminarList = document.querySelectorAll('.btnEliminar');

        btnEliminarList.forEach(function (btnEliminar) {
            btnEliminar.addEventListener('click', function () {
                let registroId = this.getAttribute('data-id');
                confirmarEliminacion(registroId);
            });
        });

        function confirmarEliminacion(registroId) {

            Swal.fire({
                title: 'Esta seguro de eliminar el registro?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Sí',
                cancelButtonText: 'No'
            }).then((resultado) => {
                if (resultado.isConfirmed) {
                    eliminarRegistro(registroId);
                }
            });
        }

        function eliminarRegistro(registroId) {
            const form = document.createElement('form');
            form.method = 'post';
            form.action = '@Model.Controlador/Delete';
            const hiddenField = document.createElement('input');
            hiddenField.type = 'hidden';
            hiddenField.name = 'id';
            hiddenField.value = registroId;
            form.appendChild(hiddenField);
            document.body.appendChild(form);
            form.submit();
        }
    });
</script>

Veterinaria WebApp/VeterinariaWebApp.ClientMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VeterinariaWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VeterinariaWebApp.ClientMvc.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/open-iconic@1.1.1/font/css/open-iconic-bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VeterinariaWebApp.ClientMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mascotas" asp-action="Index">Mascotas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Citas" asp-action="Index">Citas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMascotas" asp-action="Index">Tipo Mascotas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Servicios" asp-action="Index">Servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VeterinariaWebApp.ClientMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>